<a href="https://colab.research.google.com/github/matheusgustavo23/ciencia-de-dados-unijui/blob/main/Atividade_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

colunas = ['Acidez Fixa','Acidez Volátil','Acidez Cítrica','Açucar Residual','Cloreto','Livre de Dióxido de Enxofre','Dióxido de Enxofre Total','Densidade','pH','Sulfato','Álcool','Qualidade']
df_vinhos = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv', names = colunas, sep = ';', skiprows=1)
df_vinhos.head()

,Acidez Fixa,Acidez Volátil,Acidez Cítrica,Açucar Residual,Cloreto,Livre de Dióxido de Enxofre,Dióxido de Enxofre Total,Densidade,pH,Sulfato,Álcool,Qualidade
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [ ]:
condicoes = [df_vinhos['Qualidade'] >= 7.0, df_vinhos['Qualidade'] >= 5.0, df_vinhos['Qualidade'] < 5.0]
notas = ['Alta', 'Média', 'Baixa']

df_vinhos['Classificação'] = np.select(condicoes, notas, default = 'Desconhecido')
df_vinhos.head(n = 10)

,Acidez Fixa,Acidez Volátil,Acidez Cítrica,Açucar Residual,Cloreto,Livre de Dióxido de Enxofre,Dióxido de Enxofre Total,Densidade,pH,Sulfato,Álcool,Qualidade,Classificação
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,Média
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,Média
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,Média
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,Média
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,Média
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5,Média
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5,Média
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7,Alta
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7,Alta
9,7.5,0.50,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5,Média

In [39]:
X = df_vinhos[df_vinhos.columns.difference(['Classificação', 'Qualidade'])].values
print(f'X: {X}')

y = df_vinhos['Classificação'].values
print(f'Y: {y}')

X: [[ 0.     7.4    0.7   ...  0.56   3.51   9.4  ]
 [ 0.     7.8    0.88  ...  0.68   3.2    9.8  ]
 [ 0.04   7.8    0.76  ...  0.65   3.26   9.8  ]
 ...
 [ 0.13   6.3    0.51  ...  0.75   3.42  11.   ]
 [ 0.12   5.9    0.645 ...  0.71   3.57  10.2  ]
 [ 0.47   6.     0.31  ...  0.66   3.39  11.   ]]
Y: ['Média' 'Média' 'Média' ... 'Média' 'Média' 'Média']

In [40]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

vinho_classificador = KNeighborsClassifier(n_neighbors = 5)
vinho_classificador.fit(X, y)

KNeighborsClassifier()

In [41]:
score_dt = cross_val_score(vinho_classificador, X, y, scoring = 'accuracy', cv =5)
print(score_dt.mean())

0.7955211598746081

In [43]:
for i in range(1, 11):
    vinho_classificador = KNeighborsClassifier(n_neighbors = i)
    vinho_classificador.fit(X, y)
    score_dt = cross_val_score(vinho_classificador, X, y, scoring='accuracy', cv=5)
    print(f'Vizinhos: {i} Acurácia: {score_dt.mean()}')

Vizinhos: 1 Acurácia: 0.7461010971786834
Vizinhos: 2 Acurácia: 0.7060697492163011
Vizinhos: 3 Acurácia: 0.7848863636363637
Vizinhos: 4 Acurácia: 0.7773824451410658
Vizinhos: 5 Acurácia: 0.7955211598746081
Vizinhos: 6 Acurácia: 0.7955172413793103
Vizinhos: 7 Acurácia: 0.806773119122257
Vizinhos: 8 Acurácia: 0.810521159874608
Vizinhos: 9 Acurácia: 0.8123922413793105
Vizinhos: 10 Acurácia: 0.8155172413793104